server:
  port: 80

spring:
  application:
    name: cloud-consumer-order


    
  cloud:
    consul:
      host: centos.cnx.com
      port: 8500
      discovery:
        service-name: ${spring.application.name}