server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment


    
  cloud:    consul:      host: centos.cnx.com
      port: 8500
      discovery:        service-name: ${spring.application.name}
          
      