server:
  port: 80

spring:
  application:
    name: cloud-consumer-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localvm.cnx.com:1433;DatabaseName=test
    username: sa
    password: Passw0rd
    
  cloud:
    zookeeper:
      connect-string: 192.168.213.119:2181


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.atguigu.springcloud.entities